# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_AlIpAkUn4cB-K7oB-_AyMM4SDPiuXA
"""

from collections import defaultdict

log_file = "auth.log"  # Log dosyasının adı
threshold = 5  # Bir IP'den 5'ten fazla başarısız deneme brute force sayılacak

# IP'lere göre deneme sayısı
failed_attempts = defaultdict(int)

with open(log_file, "r") as file:
    for line in file:
        if "Failed password" in line:
            parts = line.split("from")
            if len(parts) > 1:
                ip = parts[1].split()[0]
                failed_attempts[ip] += 1

# Sonuçları yazdır
print("Brute force şüphesi olan IP adresleri:")
for ip, count in failed_attempts.items():
    if count >= threshold:
        print(f"{ip} → {count} failed attempts")